
//PUCHARSE
export const GET_PURCHASE = "api/getPurchase";

//Landing
export const LANDING_REQUEST = "LANDING_REQUEST";
export const LANDING_REQUEST_SUCCESS = "LANDING_REQUEST_SUCCESS";
export const LANDING_REQUEST_FAILED = "LANDING_REQUEST_FAILED";

//PRODUCT
export const PRODUCTS_REQUEST = "PRODUCTS_REQUEST";
export const PRODUCTS_REQUEST_SUCCESS = "PRODUCTS_REQUEST_SUCCESS";
export const PRODUCTS_REQUEST_FAILED = "PRODUCTS_REQUEST_FAILED";

//CATEGORY
export const CATEGORY_REQUEST = "CATEGORY_REQUEST";
export const CATEGORY_REQUEST_SUCCESS = "CATEGORY_REQUEST_SUCCESS";
export const CATEGORY_REQUEST_FAILED = "CATEGORY_REQUEST_FAILED";

//SUBCATEGORY
export const SUBCATEGORY_REQUEST = "SUBCATEGORY_REQUEST";
export const SUBCATEGORY_REQUEST_SUCCESS = "SUBCATEGORY_REQUEST_SUCCESS";
export const SUBCATEGORY_REQUEST_FAILED = "SUBCATEGORY_REQUEST_FAILED";

//PURCHASE
export const PURCHASE_REQUEST = "PURCHASE_REQUEST";
export const PURCHASE_REQUEST_SUCCESS = "PURCHASE_REQUEST_SUCCESS";
export const PURCHASE_REQUEST_FAILED = "PURCHASE_REQUEST_FAILED";

export const ORDER_BY = "filter/AllProdutcs";
